apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-prometheus@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /v1/
            pathType: Prefix
            backend:
              service:
                name: a08-proxy
                port:
                  number: 5000
          - path: /prometheus/
            pathType: Prefix
            backend:
              service:
                name: prometheus-stack-prometheus
                port:
                  number: 9100

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-prometheus
  namespace: default # same namespace as your Ingress
spec:
  redirectRegex:
    regex: ^/prometheus$$
    replacement: /prometheus/
    permanent: true