apiVersion: v1
kind: Service
metadata:
  name: sigma-auth
spec:
  selector:
    app: sigma-auth
  ports:
    - name: rest
      port: 8002
      targetPort: 8002
    - name: grpc
      port: 50051
      targetPort: 50051
  type: LoadBalancer
