global:
  scrape_interval:     15s # Set how often Prometheus scrapes targets
  evaluation_interval: 15s # Set how often Prometheus evaluates rules

scrape_configs:
  - job_name: 'mewing-menu'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['mewing-menu:8080'] # Scrape mewing-menu metrics


  - job_name: 'ohio-order'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ohio-order:8080']

  - job_name: 'sigma-auth'
    static_configs:
      - targets: ['sigma-auth:8000']