apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: a08-proxy-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: default-strip-v1@kubernetescrd
spec:
  rules:
  - host: api.rizzserve.site
    http:
      paths:
      - path: /v1
        pathType: Prefix
        backend:
          service:
            name: a08-proxy
            port:
              number: 5000
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: default-strip-v1
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - /v1
