apiVersion: apps/v1
kind: Deployment
metadata:
  name: ohio-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ohio-db
  template:
    metadata:
      labels:
        app: ohio-db
    spec:
      containers:
        - name: postgres
          image: postgres:17
          env:
            - name: POSTGRES_DB
              value: ohio_order
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          emptyDir: {}
